-- Retire the "no-show" (ไม่มาตามนัด) booking status. The feature is removed:
-- a customer who doesn't arrive is now handled by the shop CANCELLING the
-- booking at its own discretion, so there is no longer a distinct `no_show`
-- state. Fold the existing historical rows into `cancelled` so the app's
-- BookingStatus union can drop `no_show` without leaving unrenderable rows.
--
-- NOTE: bookings.status is a Postgres ENUM (booking_status), so this file only
-- backfills the rows; the now-unused `no_show` enum VALUE is retired separately
-- in 20260607150000_drop_no_show_enum_value.sql (Postgres cannot DROP an enum
-- value in place). After this runs, no row should carry status = 'no_show'.
update public.bookings set status = 'cancelled' where status = 'no_show';
